### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nils91** [nils91/som#1]
- [x] Implement a first prototype to prove the idea
- [x] Document first version of SOM bitcode (#2, #3)
- [ ] Implement cli client
  - [x] --version
   - [x] --verbose
   - [x] --run
   - [x] --compile
   - [x] --help
   - [x] --infile
   - [x] --outfile
   - [x] --informat
   - [x] --outformat
   - [x] --heap
   - [x] --timeout
   - [x] --n
   - [ ] --params
   - [ ] ~~--stack~~
   - [ ] --check
- [ ] Formats
  - [x] bin (#2)
  - [x] ab (#2)
  - [x] hra (#34)
    - [x] hrav 
    - [ ] hrad
    - [ ] hrai (#131)
    - [x] hras
    - [x] hrac
  - [ ] hrb
    - [x] hrbs
      - [x] Commands
      - [x] Automatic (static) allocation of memory addresses to Symbols
    - [ ] ~~hre~~ 
    - [ ] hrbp
      - [ ] Pointers and Deref
      - [ ] Value insertion 
    - [ ] hrbc
      - [ ] Command overloading 
  - [ ] hrc
  - [ ] hrd
  - [ ] ~~hre~~
  - [ ] ~~tm~~
- [x] Directives
  - [x] n
  - [x] start
  - [x] heap / an
  - [x] cont
- [ ] Compile
  - [x] bin -> ab
  - [x] ab -> bin
  - [x] hra -> ab
  - [ ] ~~hrab -> ab ~~
  - [x] hrad -> hrab
  - [x] hrbs -> hrad
  - [ ] hrbe -> hrbs
  - [ ] hrc -> hrbe
  - [ ] hrd -> hrc
  - [ ] ~~hre -> hrd~~
  - [ ] ab -> tm
  - [ ] bin -> ANSI C
  - [x] a -> c if a -> b and b -> c
- [ ] Write hooks 
  - [x] Implemented in runtime 
- [ ] Bit ranges
- [x] Deref
- [ ] Aspirational
  - [ ] Compile
    - [ ] ANSI C -> hrd
    - [ ] Java -> ANSI C
- [ ] Ongoing
  - [ ] More tests
  - [ ] Document current features
