### ISSUE TITLE
HRBP Language feature planning

### ISSUE THREAD

**Issue by nils91** [nils91/som#54]
- [ ] Nested command definitions (#41)
- [ ] Binary value insertion (see also #1)
- [ ] Pointers (see also #1, #40)
- [ ] Simple types
- [ ] Command overloading
- [ ] Composites
- [ ] Copy parameters
